### ISSUE TITLE
Syntax highlighting for Styled Components

### ISSUE THREAD

**Issue by SeanGroff** [Binaryify/OneDark-Pro#77] opened 2017-05-25 15:25 UTC
Syntax highlighting for [Styled Components](https://www.styled-components.com/docs/basics)would be amazing.

**Comment by jens1o** [comment] 2017-05-26 06:11
will take a look. @Binaryify Maybe you want to add me as a collaborator, so I can assign myself?

**Comment by Binaryify** [comment] 2017-05-26 06:29
@jens1o 
Done

**Comment by jens1o** [comment] 2017-05-26 06:30
Thx.

**Comment by will-stone** [comment] 2017-05-26 13:07
Is this not covered by this extension? https://github.com/styled-components/vscode-styled-components

**Comment by SeanGroff** [comment] 2017-05-26 13:10
Yes this is why I closed this issue. I discovered the Babel ES6/ES7 plugin was the issue. I disabled this extension and now syntax highlighting works.

**Comment by jens1o** [comment] 2017-05-26 13:11
Yes, you're both true.

But to be honest, this doesn't look good at all:
![image](https://cloud.githubusercontent.com/assets/11234139/26495871/99f2a21c-4225-11e7-814a-48d89fe8b1a0.png)

**Comment by will-stone** [comment] 2017-05-26 13:12
Ah, you commented as I closed it. Looks ok to me. Feel free to reopen if you are able to improve :-)

**Comment by jens1o** [comment] 2017-05-26 13:13
Well, the problem is that the grammar is pretty poor, so everything must be really general... 😢

**Comment by Binaryify** [comment] 2017-07-04 02:52
@SeanGroff 
I think if you install the styled-components extend will be better
https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components

![image](https://user-images.githubusercontent.com/12221718/27813174-a39dc39c-60a6-11e7-8002-8063989a34a2.png)

**Comment by SeanGroff** [comment] 2017-07-04 03:03
Yep I've always used the styled-components extension @Binaryify. 
The issue I experienced was the Babel ES6/ES7 VS Code extension was conflicting with the styled-components extension. 
Thank you for the suggestion though.

**Closed** 2017-07-04 03:04 UTC
Labels: enhancement
