### ISSUE TITLE
one dark pro vivid and blod disappear.

### ISSUE THREAD

**Issue by Rainy-Bear** [Binaryify/OneDark-Pro#350] opened 2019-11-18 05:09 UTC

**Comment by Binaryify** [comment] 2019-11-18 05:48
check the release note 
https://github.com/Binaryify/OneDark-Pro/blob/master/releaseNote.md

**Comment by daeschlerdavid** [comment] 2019-11-18 08:29
same issue, and changing vivid as specified in the changelog have 0 effect (tested on 2 different PC)

**Comment by Binaryify** [comment] 2019-11-18 08:42
@daeschlerdavid have you rereload vscode

**Comment by daeschlerdavid** [comment] 2019-11-18 08:52
it is working at my workplace... need to try again at home

**Comment by daeschlerdavid** [comment] 2019-11-18 08:58
@Binaryify is it possible that it's working only when VScode running in local ?
Activating vivid in local mode triggers VScode to ask me to reload.
In remote dev mode, nothing happens.

**Comment by kraftwerk28** [comment] 2019-11-18 09:04
Same issue, changing oneDarkPro's settings results in no effect (theme's settings always look like default)

**Comment by Amuou** [comment] 2019-11-18 09:09
Same issue, bold / vivid / italic settings are not applied.

**Comment by Binaryify** [comment] 2019-11-18 09:20
@daeschlerdavid yes, I just found that it can't work fine in remote dev mode, will try use other way to update the theme

**Comment by kraftwerk28** [comment] 2019-11-18 09:26
> Same issue, changing oneDarkPro's settings results in no effect (theme's settings always look like default)

Currently, it's fixable by rolling back to 3.0.0 (through extensions menu)

**Comment by Binaryify** [comment] 2019-11-18 09:34
@kraftwerk28 have you try uninstall and reinstall

**Comment by ntomka** [comment] 2019-11-18 10:02
There are clearly a problem in 3.0.1 which is not exists in 3.0.0. I have log from from dev tools console:

```
[Extension Host] Here is the error stack:  Error: Cannot find module './webviews/releasenotes'
Require stack:
- /home/nagta/.vscode/extensions/zhuangtongfa.material-theme-3.0.1/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.Module._load (internal/modules/cjs/loader.js:531:27)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/home/nagta/.vscode/extensions/zhuangtongfa.material-theme-3.0.1/out/extension.js:17:24)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
	at Module.load (internal/modules/cjs/loader.js:645:32)
	at Function.Module._load (internal/modules/cjs/loader.js:560:12)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:719)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:32:963)
	at d._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:766:484)
	at d._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:677:300)
	at d._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:360)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:296)
	at t.ExtensionsActivator._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:506:21)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:632
	at Array.map (<anonymous>)
	at t.ExtensionsActivator._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:620)
	at t.ExtensionsActivator.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:503:413)
	at d._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:675:24)
	at d._handleEagerExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:678:800)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:682:215
```

**Comment by Binaryify** [comment] 2019-11-18 10:04
@ntomka thanks for the log, I know what the problem is

**Comment by Binaryify** [comment] 2019-11-18 10:06
the problem is the Linux is case sensitive, but windows/Mac is not, so the probile will happen in Linux and remote dev mode

**Comment by Binaryify** [comment] 2019-11-18 10:09
just release a new version v3.0.2, you guys can check if it work now
@ntomka 
@kraftwerk28 @daeschlerdavid @Amuou  @Rainy-Bear

**Comment by ntomka** [comment] 2019-11-18 10:15
I tried to reinstall the extension, but still no luck. :(

```
[Extension Host] Activating extension `zhuangtongfa.material-theme` failed:  Cannot find module './webviews/releasenotes'
Require stack:
- /home/nagta/.vscode/extensions/zhuangtongfa.material-theme-3.0.2/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
```

**Comment by Binaryify** [comment] 2019-11-18 10:15
just release a new version v3.0.3, you guys can check if it work now
@ntomka 
@kraftwerk28 @daeschlerdavid @Amuou  @Rainy-Bear

**Comment by ntomka** [comment] 2019-11-18 10:18
3.0.3 works like a charm! Thanks! :handshake:

**Comment by kraftwerk28** [comment] 2019-11-18 10:20
> just release a new version v3.0.3, you guys can check if it work now
> @ntomka
> @kraftwerk28 @daeschlerdavid @Amuou @Rainy-Bear

3.0.3 fixed the issue, thanks!

**Comment by Amuou** [comment] 2019-11-18 10:50
> just release a new version v3.0.3, you guys can check if it work now
> @ntomka
> @kraftwerk28 @daeschlerdavid @Amuou @Rainy-Bear

It works, thanks for the quick fix!

**Comment by daeschlerdavid** [comment] 2019-11-18 11:50
confirmed working (also on visual studio online)

**Comment by athrunsun** [comment] 2019-11-18 16:22
Hey guys,

I'm using VSCode 1.40.1 on Windows 10 1903, with this extension's version 3.0.3 installed.

The problem is, UI color theme still doesn't fully take effect in remote dev env, here is the screenshot:

![1](https://user-images.githubusercontent.com/1920454/69069867-2f02b200-0a62-11ea-88b9-8b0a4053c0be.png)

I have these theme related settings:

```json
{
    "oneDarkPro.editorTheme": "Onedark Pro",
    "oneDarkPro.italic": false,
    "oneDarkPro.vivid": true,
    "workbench.colorTheme": "One Dark Pro",
}
```

**Comment by benlavender** [comment] 2019-11-18 21:11
So you’ve merged those themes into the settings only area rather than having multiple selectable themes; I get it.

**Comment by Binaryify** [comment] 2019-11-19 01:20
@benlavender that previous directory is not require

**Closed** 2019-12-05 02:19 UTC
