### ISSUE TITLE
Blue borders on tabs

### ISSUE THREAD

**Issue by tom-sherman** [Binaryify/OneDark-Pro#229] opened 2018-06-14 08:27 UTC
![image](https://user-images.githubusercontent.com/9257001/41400418-fce740e0-6fb4-11e8-822c-b962987d9c99.png)

VSCode version: 1.24.1 (Windows 10)
One Dark Pro version: 2.14.0

This doesn't happen on One Dark Pro Vivid. Is it a bug?

**Comment by JonGarbayo** [comment] 2018-06-14 08:49
It's not a bug, look at this commit: https://github.com/Binaryify/OneDark-Pro/commit/6ca587a0c8467df610fda365663e74c5dd2dbfba

But yeah, it looks like a bug.
The borders in Atom are pretty, but in VS Code it's not the case, IMO.

**Comment by Binaryify** [comment] 2018-06-14 08:53
I just change it back

**Comment by JonGarbayo** [comment] 2018-06-14 08:57
Sorry, I just checked in Atom: the blue border is only on the active tab, not all of them.
If it's possible in VS Code, it could be pretty, I think :)

**Comment by tom-sherman** [comment] 2018-06-14 11:22
@Binaryify Thanks for this! Any idea when it will be released?

**Comment by Binaryify** [comment] 2018-06-14 13:40
@tom-sherman it had already released

**Closed** 2018-09-26 13:48 UTC
