### ISSUE TITLE
about the markdown

### ISSUE THREAD

**Issue by blackier** [Binaryify/OneDark-Pro#159] opened 2017-11-17 11:45 UTC
can you support more syntax for the markdown?
I use the vscode to write markdown,but the onedark-pro don't have a good support for mardown.So I think you can support more syntax for the markdown. Or you have a test that use the vscode to write markdown,then you may want to do it.

**Comment by Binaryify** [comment] 2017-11-18 07:52
have any good idea?

**Comment by Binaryify** [comment] 2017-11-25 07:16
can you provide some screenshot?

**Comment by svipben** [comment] 2018-03-13 07:21
@blackier Can you reproduce this again? Also, could you send us the markdown itself to see what colors are missing?

**Comment by blackier** [comment] 2018-03-18 05:48
@Binaryify @svipben I am sorry,as a newcomer, I don't visit GitHub so often that I didn't see your news in time.The picture is as follows:
![eg01](https://user-images.githubusercontent.com/26369551/37563005-bd10b49e-2ab1-11e8-8411-509b96a4f2d2.png)
![eg02](https://user-images.githubusercontent.com/26369551/37563006-c683ba3a-2ab1-11e8-8fd7-c510d2901257.png)
![eg03](https://user-images.githubusercontent.com/26369551/37563009-ce692e6a-2ab1-11e8-9277-b90d0ee134a7.png)
My idea is that the code snippet can be as highlighted as the type of the identifier 
```c
`int main(){return 0;}`
```
It's great like this! And the latest updates, Obviously, the support for md is better and I like it very much,thank you!

**Comment by svipben** [comment] 2018-03-18 07:51
@blackier Can you send us the code instead of pictures? I will test it outside MD and inside MD.

**Comment by blackier** [comment] 2018-03-19 11:06
@svipben Yes.
c
```c
struct proc_struct {
    enum proc_state state;                      // Process state
    int pid;                                    // Process ID
    int runs;                                   // the running times of Proces
    uintptr_t kstack;                           // Process kernel stack
    volatile bool need_resched;                 // bool value: need to be rescheduled to release CPU?
    struct proc_struct *parent;                 // the parent process
    struct mm_struct *mm;                       // Process's memory management field
    struct context context;                     // Switch here to run process
    struct trapframe *tf;                       // Trap frame for current interrupt
    uintptr_t cr3;                              // CR3 register: the base addr of Page Directroy Table(PDT)
    uint32_t flags;                             // Process flag
    char name[PROC_NAME_LEN + 1];               // Process name
    list_entry_t list_link;                     // Process link list
    list_entry_t hash_link;                     // Process hash list
};
```
c
```c
int
do_fork(uint32_t clone_flags, uintptr_t stack, struct trapframe *tf) {
    int ret = -E_NO_FREE_PROC;
    struct proc_struct *proc;
    if (nr_process >= MAX_PROCESS) {
        goto fork_out;
    }
    ret = -E_NO_MEM;

}
```
This is good.
asm
```s
    movl %esp, 4(%eax)
    movl %ebx, 8(%eax)
    movl %ecx, 12(%eax)
    movl %edx, 16(%eax)
    movl %esi, 20(%eax)
    movl %edi, 24(%eax)
    movl %ebp, 28(%eax)
```

**Comment by svipben** [comment] 2018-03-19 17:11
@blackier This is the problem with VS Code itself.

Test it with Dark+ default theme and you will see. But we definitely need to fix it somehow by making it better because currently, it's very bad...

I guess it makes sense to open issue in VS Code to fix their scopes of Markdown files.

**Comment by blackier** [comment] 2018-03-20 10:45
@svipben Got it, look forward to the update.

**Comment by svipben** [comment] 2018-03-25 16:24
Already opened an issue in VS Code. I also created my own One Dark theme which will have proper coloring to match Atom's One Dark as much as possible. Currently on my to-do list is to improve C and C++ coloring, I believe @blackier you will be interested to try my theme. I created it because I have a different vision.

Repo: https://github.com/svipben/vscode-one-dark-theme
Theme: https://marketplace.visualstudio.com/items?itemName=svipben.one-dark

**Comment by jens1o** [comment] 2018-03-25 16:29
Please understand that we do not allow ads for other products.

**Comment by svipben** [comment] 2018-03-25 16:30
@jens1o I'm always open to cooperate and merge our products into one.

**Comment by jens1o** [comment] 2018-03-25 16:32
@svipben Then feel free to maintain your fork and open pull requests at our end. It's *you* who started their own theme, so *we* do not need to give up our passion.

**Closed** 2019-03-13 08:01 UTC
